version: "3.9"
   
services:
  nginx:
    build: ./nginx
    ports:
      - 1300:80
    volumes:
      - static_volume:/app/staticfiles
    command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - web
    restart: "on-failure"
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: ./wharehouseWebApp
    command: gunicorn --bind :8000 --workers 3 wharehouseWebApp.wsgi
    volumes:
      - .:/code
      - static_volume:/app/staticfiles
    expose:
      - 8000
    depends_on:
      - setup
  setup:
    build: ./wharehouseWebApp
    environment:
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
    command: >
      sh -c 
          "./wait-for-it.sh db:5432 -- python manage.py makemigrations &&
          python manage.py migrate &&
          python manage.py collectstatic --noinput &&
          python manage.py createsuperuser --noinput"
          
    volumes:
      - .:/code
      - static_volume:/app/staticfiles
    links:
      - db
    depends_on:
      - db
volumes:
    static_volume: